name: Deploy mdBook

on:
    push:
        branches: [main]
        paths:
            - "docs-book/**"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    build-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup mdBook
              uses: peaceiris/actions-mdbook@v2
              with:
                  mdbook-version: "latest" # or a pinned version like '0.4.52'

            - name: Build book
              working-directory: docs-book
              run: mdbook build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs-book/book
